web/router.ex
defmodule Constable.Router do
  use Phoenix.Router
  use Honeybadger.Plug

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash

    if Mix.env == :test do
      plug Constable.Plugs.SetUserIdFromParams
    end

    plug Constable.Plugs.FetchCurrentUser
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Constable do
    pipe_through :browser

    resources "/session", SessionController, only: [:new, :delete], singleton: true

    resources "/unsubscribe", UnsubscribeController, only: [:show]

    if Mix.env == :dev do
      get "/emails/:email_name", EmailPreviewController, :show
    end
  end

  scope "/", Constable do
    pipe_through [:browser, Constable.Plugs.RequireWebLogin]

    get "/", HomeController, :index

    resources "/announcements", AnnouncementController, only: [:index, :show, :new, :create, :edit, :update] do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/subscriptions", SubscriptionController, singleton: true, only: [:create, :delete]
    end
    resources "/settings", SettingsController, singleton: true, only: [:show, :update]
    resources "/interests", InterestController, only: [:index, :show], param: "id_or_name" do
      resources "/slack_channel", SlackChannelController, singleton: true, only: [:edit, :update, :delete]
      resources "/user_interest", UserInterestController, singleton: true, only: [:create, :delete]
    end
    resources "/search", SearchController, singleton: true, only: [:show, :new]
    resources "/recipients_preview", RecipientsPreviewController, singleton: true, only: [:show]
    resources "/user_activations", UserActivationController, only: [:index, :update]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", Constable do
    pipe_through :api

    resources "/email_forwards", EmailForwardController, only: [:create]
    resources "/email_replies", EmailReplyController, only: [:create]
  end

  scope "/auth", alias: Constable do
    pipe_through [:browser]

    get "/", AuthController, :index
    get "/javascript_callback", AuthController, :javascript_callback
    get "/browser_callback", AuthController, :browser_callback
  end

  scope "/auth", alias: Constable do
    pipe_through :api

    post "/mobile_callback", AuthController, :mobile_callback
  end

  scope "/api", as: :api, alias: Constable.Api do
    pipe_through [:api, Constable.Plugs.RequireApiLogin]

    resources "/announcements", AnnouncementController
    resources "/comments", CommentController, only: [:create]
    resources "/interests", InterestController, only: [:index, :show, :update]
    resources "/searches", SearchController, only: [:create]
    resources "/subscriptions", SubscriptionController, only: [:index, :create, :delete]
    resources "/user_interests", UserInterestController, only: [:index, :show, :create, :delete]
    resources "/users", UserController, only: [:index, :show]
    resources "/users", UserController, only: [:update], singleton: true
  end

  scope "/api", as: :api, alias: Constable.Api do
    pipe_through :api

    resources "/users", UserController, only: [:create]
  end
end

web/views/layout_view.ex
defmodule Constable.LayoutView do
  use Constable.Web, :view
end

web/templates/layout/_analytics.html.eex
<% if System.get_env("SEGMENT_KEY") do %>
  <script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
  analytics.load("<%= System.get_env("SEGMENT_KEY") %>");
  analytics.page()
  }}();
  </script>
<% end %>

web/templates/layout/_flashes.html.eex
<%= if get_flash(@conn, :info) do %>
  <div class="flash flash-info">
    <%= get_flash(@conn, :info) %>
  </div>
<% end %>

<%= if get_flash(@conn, :error) do %>
  <div class="flash flash-error">
    <%= get_flash(@conn, :error) %>
  </div>
<% end %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Constable</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script>window.userToken = "<%= @current_user.token %>";</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="<%= Application.fetch_env!(:constable, :shubox_script_url) %>"></script>
  </head>

  <body>
    <div class="page">
      <header class="main-header">
        <%= link "#Constable", to: "/", class: "logo" %>

        <ul class="navigation right">
          <li>
            <%= form_tag search_path(@conn, :show), method: :get do %>
              <input
                class="header-search-input"
                name="query"
                placeholder="Search announcements..."
                type="text"
                value="<%= @conn.params["query"] %>"
              />
            <% end %>
          </li>
          <li>
            <%= link to: announcement_path(@conn, :new), class: "button button-small button-secondary button-icon" do %>
              <img src="/images/icon-plus-white.svg" />
            <% end %>
          </li>
          <li>
            <%= link to: settings_path(@conn, :show), class: "settings-gravatar remote-append" do %>
              <img
                src="<%= gravatar(@conn.assigns.current_user) %>"
                class="current-user-gravatar"
              />
            <% end %>
          </li>
        </ul>
      </header>
      <%= render "_flashes.html", conn: @conn %>
      <%= render "_analytics.html" %>

      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>

web/templates/layout/login.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Constable</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "_flashes.html", conn: @conn %>

    <div class="login-page">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>