web/router.ex
defmodule Constable.Router do
  use Phoenix.Router
  use Honeybadger.Plug

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash

    if Mix.env == :test do
      plug Constable.Plugs.SetUserIdFromParams
    end

    plug Constable.Plugs.FetchCurrentUser
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Constable do
    pipe_through :browser

    resources "/session", SessionController, only: [:new, :delete], singleton: true

    resources "/unsubscribe", UnsubscribeController, only: [:show]

    if Mix.env == :dev do
      get "/emails/:email_name", EmailPreviewController, :show
    end
  end

  scope "/", Constable do
    pipe_through [:browser, Constable.Plugs.RequireWebLogin]

    get "/", HomeController, :index

    resources "/announcements", AnnouncementController, only: [:index, :show, :new, :create, :edit, :update] do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/subscriptions", SubscriptionController, singleton: true, only: [:create, :delete]
    end
    resources "/settings", SettingsController, singleton: true, only: [:show, :update]
    resources "/interests", InterestController, only: [:index, :show], param: "id_or_name" do
      resources "/slack_channel", SlackChannelController, singleton: true, only: [:edit, :update, :delete]
      resources "/user_interest", UserInterestController, singleton: true, only: [:create, :delete]
    end
    resources "/search", SearchController, singleton: true, only: [:show, :new]
    resources "/recipients_preview", RecipientsPreviewController, singleton: true, only: [:show]
    resources "/user_activations", UserActivationController, only: [:index, :update]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", Constable do
    pipe_through :api

    resources "/email_forwards", EmailForwardController, only: [:create]
    resources "/email_replies", EmailReplyController, only: [:create]
  end

  scope "/auth", alias: Constable do
    pipe_through [:browser]

    get "/", AuthController, :index
    get "/javascript_callback", AuthController, :javascript_callback
    get "/browser_callback", AuthController, :browser_callback
  end

  scope "/auth", alias: Constable do
    pipe_through :api

    post "/mobile_callback", AuthController, :mobile_callback
  end

  scope "/api", as: :api, alias: Constable.Api do
    pipe_through [:api, Constable.Plugs.RequireApiLogin]

    resources "/announcements", AnnouncementController
    resources "/comments", CommentController, only: [:create]
    resources "/interests", InterestController, only: [:index, :show, :update]
    resources "/searches", SearchController, only: [:create]
    resources "/subscriptions", SubscriptionController, only: [:index, :create, :delete]
    resources "/user_interests", UserInterestController, only: [:index, :show, :create, :delete]
    resources "/users", UserController, only: [:index, :show]
    resources "/users", UserController, only: [:update], singleton: true
  end

  scope "/api", as: :api, alias: Constable.Api do
    pipe_through :api

    resources "/users", UserController, only: [:create]
  end
end

web/models/announcement.ex
defmodule Constable.Announcement do
  use Constable.Web, :model
  alias Constable.Comment
  alias Constable.User
  alias Constable.Subscription
  alias Constable.Interest
  alias Constable.AnnouncementInterest

  schema "announcements" do
    field :title
    field :body
    field :last_discussed_at, Ecto.DateTime, autogenerate: true
    timestamps

    belongs_to :user, User
    has_many :comments, Comment, on_delete: :delete_all
    has_many :subscriptions, Subscription, on_delete: :delete_all
    many_to_many :interests, Interest, join_through: AnnouncementInterest
    has_many :interested_users, through: [:interests, :users]
  end

  def update_changeset(announcement, params) do
    announcement
    |> cast(params, ~w(title body))
    |> validate_required([:title, :body])
  end

  def create_changeset(announcement, params) do
    announcement
    |> cast(params, ~w(title body user_id))
    |> validate_required([:title, :body])
  end

  def last_discussed_first(query \\ __MODULE__) do
    query |> order_by(desc: :last_discussed_at)
  end

  def with_announcement_list_assocs(query \\ __MODULE__) do
    from q in query, preload: [
      :user,
      interests: ^Interest.ordered_by_name,
      comments: ^newest_comments_first,
      comments: :user
    ]
  end

  def search(query \\ __MODULE__, search_term) do
    search_term = search_term |> prepare_for_tsquery

    from(a in query,
      where: fragment("to_tsvector('english', ?) || to_tsvector('english', ?) @@ plainto_tsquery('english', ?)",
        a.title,
        a.body,
        ^search_term
      )
    )
  end

  defp prepare_for_tsquery(search_term) do
    search_term
    |> String.split(" ", trim: true)
    |> Enum.intersperse(" & ")
    |> Enum.join("")
  end

  defp newest_comments_first do
    from(c in Comment, order_by: [asc: c.inserted_at])
  end
end

web/models/serializers/announcement.ex
defimpl Poison.Encoder, for: Constable.Announcement do
  alias Constable.Repo
  @attributes ~W(
    id
    title
    body
    user
    comments
    interests
    inserted_at
    updated_at
  )a

  def encode(announcement, _options) do
    announcement
    |> Repo.preload([:comments, :user, :interests])
    |> Map.take(@attributes)
    |> set_interests
    |> Poison.encode!
  end

  def set_interests(announcement) do
    interest_names = Enum.map(announcement.interests, fn (interest) -> interest.name end)
    Map.put(announcement, "interests", interest_names)
  end
end

web/controllers/announcement_controller.ex
defmodule Constable.AnnouncementController do
  use Constable.Web, :controller

  alias Constable.User
  alias Constable.Services.AnnouncementUpdater

  alias Constable.{Announcement, Comment, Interest, Subscription}
  alias Constable.Services.AnnouncementCreator

  def index(conn, %{"all" => "true"} = params) do
    index_page = all_announcements |> Repo.paginate(params)

    conn
    |> assign(:announcements, index_page.entries)
    |> assign(:show_all, true)
    |> assign(:current_user, preload_interests(conn.assigns.current_user))
    |> assign(:index_page, index_page)
    |> render("index.html")
  end

  def index(conn, %{"interest" => interest, "page" => page}) do
    conn
    |> redirect(to: interest_path(conn, :show, interest, page: page))
  end

  def index(conn, params) do
    index_page = my_announcements(conn) |> Repo.paginate(params)

    conn
    |> assign(:announcements, index_page.entries)
    |> assign(:show_all, false)
    |> assign(:current_user, preload_interests(conn.assigns.current_user))
    |> assign(:index_page, index_page)
    |> render("index.html")
  end

  def show(conn, %{"id" => id}) do
    announcement = Repo.get!(Announcement.with_announcement_list_assocs, id)
    comment = Comment.create_changeset(%{})
    subscription = Repo.get_by(Subscription,
      announcement_id: announcement.id,
      user_id: conn.assigns.current_user.id
    )

    conn
    |> render("show.html",
      announcement: announcement,
      comment_changeset: comment,
      subscription: subscription,
      users: Repo.all(User.active),
    )
  end

  def new(conn, _params) do
    render_form(conn, "new.html", %Announcement{})
  end

  def create(conn, %{"announcement" => announcement_params}) do
    {interest_names, announcement_params} = extract_interest_names(announcement_params)
    announcement_params = announcement_params
      |> Map.put("user_id", conn.assigns.current_user.id)

    case AnnouncementCreator.create(announcement_params, interest_names) do
      {:ok, announcement} ->
        redirect(conn, to: announcement_path(conn, :show, announcement.id))
      {:error, changeset} ->
        interests = Repo.all(Interest)
        render(conn, "new.html", %{
          changeset: changeset,
          interests: interests,
          user_json: Repo.all(User),
        })
    end
  end

  def edit(conn, %{"id" => id}) do
    announcement = Repo.get!(Announcement, id) |> Repo.preload([:interests])
    render_form(conn, "edit.html", announcement)
  end

  def update(conn, %{"id" => id, "announcement" => announcement_params}) do
    current_user = conn.assigns.current_user
    announcement = Repo.get!(Announcement, id)

    {interest_names, announcement_params} = extract_interest_names(announcement_params)

    if announcement.user_id == current_user.id do
      case AnnouncementUpdater.update(announcement, announcement_params, interest_names) do
        {:ok, announcement} ->
          redirect(conn, to: announcement_path(conn, :show, announcement.id))
        {:error, _changeset} ->
          render_form(conn, "edit", announcement)
      end
    else
      conn
      |> put_flash(:error, gettext("You do not have permission to edit that announcement"))
      |> redirect(to: announcement_path(conn, :show, announcement.id))
    end
  end

  defp render_form(conn, action, announcement) do
    changeset = Announcement.create_changeset(announcement, %{})
    interests = Repo.all(Interest)
    users = Repo.all(User.active)

    render(conn, action, %{
      changeset: changeset,
      interests: interests,
      users: users,
    })
  end

  defp extract_interest_names(announcement_params) do
    interest_names = Map.get(announcement_params, "interests")
      |> String.split(",")
    announcement_params = announcement_params
      |> Map.delete("interests")

    {interest_names, announcement_params}
  end

  defp my_announcements(conn) do
    conn.assigns.current_user
    |> Ecto.assoc(:interesting_announcements)
    |> Announcement.with_announcement_list_assocs
    |> Announcement.last_discussed_first
  end

  defp all_announcements do
    Announcement.with_announcement_list_assocs
    |> Announcement.last_discussed_first
  end

  defp preload_interests(user) do
    Repo.preload user, :interests
  end
end

web/controllers/api/announcement_controller.ex
defmodule Constable.Api.AnnouncementController do
  use Constable.Web, :controller

  alias Constable.Announcement
  alias Constable.Services.AnnouncementCreator
  alias Constable.Services.AnnouncementUpdater
  alias Constable.Api.AnnouncementView

  def index(conn, _params) do
    announcements = Repo.all(Announcement)
    render(conn, "index.json", announcements: announcements)
  end

  def create(conn,
      %{"announcement" => announcement_params, "interest_names" => interest_names}) do
    current_user = current_user(conn)
    announcement_params = Map.put(announcement_params, "user_id", current_user.id)

    case AnnouncementCreator.create(announcement_params, interest_names) do
      {:ok, announcement} ->
        Constable.Endpoint.broadcast!(
          "update",
          "announcement:add",
          AnnouncementView.render("show.json", %{announcement: announcement})
        )
        conn
        |> put_status(:created)
        |> render("show.json", announcement: announcement)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(Constable.ChangesetView, "error.json", changeset: changeset)
    end
  end
  def create(conn, _params), do: send_resp(conn, 422, "")

  def show(conn, %{"id" => id}) do
    announcement = Repo.get!(Announcement, id)
    render conn, "show.json", announcement: announcement
  end

  def update(conn, %{
      "id" => id, "announcement" => announcement_params,
      "interest_names" => interest_names
    }) do

    current_user = current_user(conn)
    announcement = Repo.get!(Announcement, id)

    if announcement.user_id == current_user.id do
      case AnnouncementUpdater.update(announcement, announcement_params, interest_names) do
        {:ok, announcement} ->
          Constable.Endpoint.broadcast!(
            "update",
            "announcement:update",
            AnnouncementView.render("show.json", %{announcement: announcement})
          )
          render(conn, "show.json", announcement: announcement)
        {:error, changeset} ->
          conn
          |> put_status(:unprocessable_entity)
          |> render(Constable.ChangesetView, "error.json", changeset: changeset)
      end
    else
      unauthorized(conn)
    end
  end
  def update(conn, _params), do: send_resp(conn, 422, "")

  def delete(conn, %{"id" => id}) do
    current_user = current_user(conn)
    announcement = Repo.get!(Announcement, id)

    if announcement.user_id == current_user.id do
      Repo.delete!(announcement)
      Constable.Endpoint.broadcast!(
        "update",
        "announcement:remove",
        %{id: announcement.id}
      )
      send_resp(conn, 204, "")
    else
      unauthorized(conn)
    end
  end
end

web/views/announcement_view.ex
defmodule Constable.AnnouncementView do
  use Constable.Web, :view

  def json_interests(interests) do
    interests
    |> Enum.map(&(%{name: &1.name}))
    |> Poison.encode!
  end

  def comma_separated_interest_names(interests) when is_list(interests) do
    interests
    |> Enum.map(&(&1.name))
    |> Enum.join(",")
  end

  def comma_separated_interest_names(_), do: ""

  def class_for("all", %{params: %{"all" => "true"}}) do
    "selected"
  end
  def class_for("mine", %{params: %{"all" => "true"}}), do: nil
  def class_for("mine", _) do
    "mine selected"
  end
  def class_for(_, _), do: nil

  def interest_count_for(user) do
    length user.interests
  end

  def user_autocomplete_json(users) do
    users
    |> Enum.map(&format_user_json/1)
    |> Poison.encode!
  end

  defp format_user_json(user) do
    %{name: user.name, username: user.username, gravatar_url: gravatar(user)}
  end
end

web/templates/announcement/_comment.html.eex
<li class="comment" id="comment-<%= @comment.id %>">
  <div class="comment-information">
    <div class="author-information">
      <img class="avatar-rounded" src="<%= gravatar @comment.user %>">
      <h4 class="author"><%= @comment.user.name %></h4>
    </div>

    <div>
      <time class="comment-time">
        <a href="#comment-<%= @comment.id %>">
          <%= time_ago_in_words @comment.inserted_at %>
        </a>

      </time>
      <%= if @comment.user_id == @current_user.id do %>
        <%= link to: announcement_comment_path(Constable.Endpoint, :edit, @comment.announcement_id, @comment), class: "edit-comment", data: [role: "edit-comment"] do %>
          <%= gettext "(edit)" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="comment-body">
    <%= raw markdown_with_users(@comment.body) %>
  </div>
</li>

web/templates/announcement/_form.html.eex
<%= form_for @changeset,
  @path,
  [class: "flex-container", data: [role: "announcement-form", id: @changeset.data.id]],
  fn(f) -> %>
  <nav class="header-tags">
    <div class="header-tag header-tag-markdown active">
      <%= gettext("Markdown") %>
    </div>

    <div class="header-tag header-tag-preview">
      <%= gettext("Preview") %>
    </div>
  </nav>
  <div class="col-markdown announcement-create active">
    <div class="announcement-form">
      <%= text_input f, :title, placeholder: gettext("What are you announcing?") %>

      <section class="recipients-preview">
        Please select interests:
      </section>
      <%= text_input :announcement, :interests, value: comma_separated_interest_names(@changeset.data.interests), placeholder: gettext("Interests") %>

      <%= textarea f,
        :body,
        placeholder: gettext("Write markdown here. You can @mention specific people to notify them"),
        class: "uploadable-input"
        %>
    </div>
  </div>

  <div class="announcement-preview">
    <h1 data-role="title-preview">Preview</h1>
    <div class="markdown announcement-body" data-role="markdown-preview">
      Preview
    </div>
  </div>

  <div class="button-container">
    <button data-role="submit-announcement">
      <%= if @changeset.data.id do %>
        <%= gettext("Update Announcement") %>
      <% else %>
        <%= gettext("Create Announcement") %>
    <% end %>
    </button>
  </div>
<% end %>

<script>
  (function() {
    window.INTERESTS_NAMES = <%= raw json_interests(@interests) %>;
    var AnnouncementForm = require('web/static/js/announcement-form').default;
    new AnnouncementForm();
    require('web/static/js/announcement-form-mobile').setupForm();
    require('web/static/js/textarea-image-uploader').setupImageUploader('#announcement_body');
    require('web/static/js/user-autocomplete').autocompleteUsers(
      '#announcement_body',
      <%= raw user_autocomplete_json(@users) %>
    );
  })()
</script>

web/templates/announcement/edit.html.eex
<%= render "_form.html",
  path: announcement_path(@conn, :update, @changeset.data.id),
  conn: @conn,
  changeset: @changeset,
  interests: @interests,
  users: @users
%>

web/templates/announcement/index.html.eex
<div class="announcements">
  <nav class="segmented-control">
    <div class="container">
      <%= link gettext("All announcements"),
        to: announcement_path(@conn, :index, all: true),
        class: class_for("all", @conn)
      %>
      <%= link gettext("Your interests"),
        to: announcement_path(@conn, :index),
        class: class_for("mine", @conn)
      %>
    </div>
  </nav>

  <p class="interests-message container">
    <%= dngettext("interest-count", "You're subscribed to 1 interest.", "You're subscribed to %{count} interests.", interest_count_for(@current_user)) %>
    <%= link to: interest_path(@conn, :index), data: [role: "view-all-interests"] do %>
      <%= gettext "Manage your interests." %>
    <% end %>
  </p>

  <%= render Constable.AnnouncementListView, "index.html", conn: @conn, announcements: @announcements %>

    <div class="container pagination">
      <%= if !on_first_page?(@index_page) do %>
        <%= link gettext(""), to: announcement_path(@conn, :index, all: @show_all, page: (@index_page.page_number - 1)), class: "page-previous button button-wire" %>
      <% end %>

      <%= if !on_last_page?(@index_page) do %>
        <%= link gettext(""), to: announcement_path(@conn, :index, all: @show_all, page: (@index_page.page_number + 1)), class: "page-next button button-wire" %>
      <% end %>
    </div>
  </div>
</div>

web/templates/announcement/new.html.eex
<%= render "_form.html",
  path: announcement_path(@conn, :create),
  conn: @conn,
  changeset: @changeset,
  interests: @interests,
  users: @users
%>

web/templates/announcement/show.html.eex
<div class="announcement container" data-announcement-id="<%= @announcement.id %>">
  <header class="announcement-header">
    <div class="announcement-interests" data-role="interests">
      <%= for interest <- @announcement.interests do %>
        <%= link interest.name, to: interest_path(@conn, :show, interest), class: "announcement-interest" %>
      <% end %>
    </div>

    <div class="subscription">
      <%= if @subscription do %>
        <%= link to: announcement_subscription_path(@conn, :delete, @announcement.id),
          method: :delete,
          class: "button button-unsubscribe",
          data: [turbolinks: "refresh"] do %>
          <%= gettext("Unsubscribe") %>
        <% end %>
      <% else %>
        <%= link to: announcement_subscription_path(@conn, :create, @announcement.id),
          method: :post,
          class: "button button-subscribe",
          data: [turbolinks: "refresh"] do %>
          <%= gettext("Subscribe") %>
        <% end %>
      <% end %>
    </div>
  </header>

  <h1 data-role="title">
    <%= @announcement.title %>
    <%= if @announcement.user_id == @current_user.id do %>
      <small>
        <%= link "edit", to: announcement_path(@conn, :edit, @announcement), data: [role: "edit"] %>
      </small>
    <% end %>
  </h1>

  <div class="announcement-metadata">
    <img src="<%= gravatar @announcement.user %>" class="avatar-rounded"/>
    <h4 class="author"><%= @announcement.user.name %></h4>
    <time><%= time_ago_in_words(@announcement.inserted_at) %></time>
  </div>

  <div class="announcement-body" data-role="body">
    <%= raw markdown_with_users(@announcement.body) %>
  </div>

  <ul class="comments-list">
    <%= for comment <- @announcement.comments do %>
      <%= render "_comment.html", comment: comment, conn: @conn, current_user: @current_user %>
    <% end %>
  </ul>

  <div class="comment-new">
    <%= Constable.CommentView.render "_form.html",
      comment_changeset: @comment_changeset,
      path: announcement_comment_path(@conn, :create, @announcement),
      submit_text: gettext("Post Comment") %>
  </div>
</div>

<script>
  (function() {
    require("web/static/js/comment-form").setupNewForm(<%= raw user_autocomplete_json(@users) %>);
    require("web/static/js/syntax-highlighting").highlightSyntax('.comments-list');
  })()
</script>