web/router.ex
defmodule Constable.Router do
  use Phoenix.Router
  use Honeybadger.Plug

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash

    if Mix.env == :test do
      plug Constable.Plugs.SetUserIdFromParams
    end

    plug Constable.Plugs.FetchCurrentUser
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Constable do
    pipe_through :browser

    resources "/session", SessionController, only: [:new, :delete], singleton: true

    resources "/unsubscribe", UnsubscribeController, only: [:show]

    if Mix.env == :dev do
      get "/emails/:email_name", EmailPreviewController, :show
    end
  end

  scope "/", Constable do
    pipe_through [:browser, Constable.Plugs.RequireWebLogin]

    get "/", HomeController, :index

    resources "/announcements", AnnouncementController, only: [:index, :show, :new, :create, :edit, :update] do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/subscriptions", SubscriptionController, singleton: true, only: [:create, :delete]
    end
    resources "/settings", SettingsController, singleton: true, only: [:show, :update]
    resources "/interests", InterestController, only: [:index, :show], param: "id_or_name" do
      resources "/slack_channel", SlackChannelController, singleton: true, only: [:edit, :update, :delete]
      resources "/user_interest", UserInterestController, singleton: true, only: [:create, :delete]
    end
    resources "/search", SearchController, singleton: true, only: [:show, :new]
    resources "/recipients_preview", RecipientsPreviewController, singleton: true, only: [:show]
    resources "/user_activations", UserActivationController, only: [:index, :update]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", Constable do
    pipe_through :api

    resources "/email_forwards", EmailForwardController, only: [:create]
    resources "/email_replies", EmailReplyController, only: [:create]
  end

  scope "/auth", alias: Constable do
    pipe_through [:browser]

    get "/", AuthController, :index
    get "/javascript_callback", AuthController, :javascript_callback
    get "/browser_callback", AuthController, :browser_callback
  end

  scope "/auth", alias: Constable do
    pipe_through :api

    post "/mobile_callback", AuthController, :mobile_callback
  end

  scope "/api", as: :api, alias: Constable.Api do
    pipe_through [:api, Constable.Plugs.RequireApiLogin]

    resources "/announcements", AnnouncementController
    resources "/comments", CommentController, only: [:create]
    resources "/interests", InterestController, only: [:index, :show, :update]
    resources "/searches", SearchController, only: [:create]
    resources "/subscriptions", SubscriptionController, only: [:index, :create, :delete]
    resources "/user_interests", UserInterestController, only: [:index, :show, :create, :delete]
    resources "/users", UserController, only: [:index, :show]
    resources "/users", UserController, only: [:update], singleton: true
  end

  scope "/api", as: :api, alias: Constable.Api do
    pipe_through :api

    resources "/users", UserController, only: [:create]
  end
end

web/models/interest.ex
defmodule Constable.Interest do
  defimpl Phoenix.Param do
    def to_param(%{name: name}) do
      "#{name}"
    end
  end

  use Constable.Web, :model
  alias Constable.{Announcement, User}
  alias Constable.{AnnouncementInterest, UserInterest}

  schema "interests" do
    field :name
    field :slack_channel
    timestamps

    many_to_many :announcements, Announcement, join_through: AnnouncementInterest
    many_to_many :users, User, join_through: UserInterest
  end

  def changeset(interest \\ %__MODULE__{}, params) do
    interest
    |> cast(params, ~w(name slack_channel))
    |> validate_required(:name)
    |> update_change(:name, &String.strip(&1))
    |> update_change(:name, &String.replace(&1, "#", ""))
    |> update_change(:name, &String.replace(&1, " ", "-"))
    |> update_change(:name, &String.downcase/1)
    |> unique_constraint(:name)
  end

  def update_channel_changeset(interest, channel_name) do
    interest
    |> cast(%{slack_channel: channel_name}, ~w(slack_channel))
    |> update_change(:slack_channel, &Regex.replace(~r/^#*/, &1, "#"))
  end

  def ordered_by_name(query \\ __MODULE__) do
    from i in query, order_by: [asc: i.name]
  end
end

web/models/serializers/interest.ex
defimpl Poison.Encoder, for: Constable.Interest do
  def encode(interest, _options) do
    %{
      id: interest.id,
      name: interest.name
    } |> Poison.encode!
  end
end

web/controllers/api/interest_controller.ex
defmodule Constable.Api.InterestController do
  use Constable.Web, :controller

  alias Constable.Interest
  alias Constable.Api.InterestView

  def index(conn, _params) do
    interests = Repo.all(Interest)

    render(conn, "index.json", interests: interests)
  end

  def show(conn, %{"id" => id}) do
    interest = Repo.get!(Interest, id)
    render conn, "show.json", interest: interest
  end

  def update(conn, %{"id" => id, "channel" => channel}) do
    interest = Repo.get!(Interest, id)
    case Repo.update(Interest.update_channel_changeset(interest, channel)) do
      {:ok, interest} ->
        Constable.Endpoint.broadcast!(
          "update",
          "interest:update", 
          InterestView.render("show.json", %{interest: interest})
        )
        render(conn, "show.json", interest: interest)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(Constable.ChangesetView, "error.json", changeset: changeset)
    end
  end
end

web/controllers/interest_controller.ex
defmodule Constable.InterestController do
  use Constable.Web, :controller

  alias Constable.{Announcement, Interest}

  def index(conn, _params) do
    conn
    |> assign(:current_user, preload_interests(conn.assigns.current_user))
    |> assign(:interests, all_interests)
    |> render("index.html")
  end

  def show(conn, params) do
    interest = get_interest_by_id_or_name(params["id_or_name"])
    interest_page = sorted_announcements(interest) |> Repo.paginate(params)

    conn
    |> assign(:current_user, preload_interests(conn.assigns.current_user))
    |> assign(:announcements, interest_page.entries)
    |> assign(:interest_page, interest_page)
    |> assign(:interest, interest)
    |> render("show.html")
  end

  defp get_interest_by_id_or_name(param) do
    case Integer.parse(param) do
      :error -> Repo.get_by!(Interest, name: param)
      {id, _} -> Repo.get!(Interest, id)
    end
  end

  defp preload_interests(user) do
    Repo.preload user, :interests
  end

  defp all_interests do
    Repo.all Interest.ordered_by_name
  end

  defp sorted_announcements(interest) do
    Ecto.assoc(interest, :announcements)
    |> Announcement.last_discussed_first
    |> Announcement.with_announcement_list_assocs
  end
end

web/views/interest_view.ex
defmodule Constable.InterestView do
  use Constable.Web, :view

  import Constable.User, only: [interested_in?: 2]
end

web/templates/interest/index.html.eex
<div class="interests container">
  <h1><%= gettext "Interests" %></h1>

  <ul class="interests-list">
    <%= for interest <- @interests do %>
      <li class="interest-list-item">
        <h3><%= link interest.name, to: interest_path(@conn, :show, interest) %></h3>
        <%= render Constable.InterestView, "subscription.html", conn: @conn, interest: interest, current_user: @current_user %>
      </li>
    <% end %>
  </ul>
</div>

web/templates/interest/show.html.eex
<div class="page-interest">
  <div class="interest container">
    <div class="interest-list-item">
      <h1><%= @interest.name %></h1>
      <%= render Constable.InterestView, "subscription.html", conn: @conn, interest: @interest, current_user: @current_user %>
    </div>

    <div class="current-channel">
      <%= link to: interest_slack_channel_path(@conn, :edit, @interest), data: [role: "edit-interest"] do %>
        <%= if @interest.slack_channel do %>
          <p data-role="current-channel">
            <%=
              gettext(
                "New announcements are posted to the %{channel} channel in Slack. Click to edit.",
                channel: @interest.slack_channel
              )
            %>
          </p>
        <% else %>
          <p data-role="current-channel">
            <%= gettext("Click here to add a slack channel webhook to this interest.") %>
          </p>
        <% end %>
      <% end %>
    </div>

    <hr/>

  </div>

  <%= render Constable.AnnouncementListView, "index.html", conn: @conn, announcements: @announcements %>

  <div class="pagination">
    <ul>
      <%= if !on_first_page?(@interest_page) do %>
        <li class="page-next">
          <%= link gettext("NEWER"), to: interest_path(@conn, :show, @interest, page: (@interest_page.page_number - 1)) %>
        </li>
      <% end %>

      <%= if !on_last_page?(@interest_page) do %>
        <li class="page-prev">
          <%= link gettext("OLDER"), to: interest_path(@conn, :show, @interest, page: (@interest_page.page_number + 1)) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

web/templates/interest/subscription.html.eex
<%= if interested_in?(@current_user, @interest) do %>
  <%= link to: interest_user_interest_path(@conn, :delete, @interest),
        method: :delete,
        class: "unsubscribe",
        data: [turbolinks: "refresh", role: "unsubscribe-from-interest"] do %>
    <span><%= gettext("Unsubscribe") %></span>
  <% end %>
<% else %>
  <%= link to: interest_user_interest_path(@conn, :create, @interest),
        method: :post,
        class: "subscribe",
        data: [turbolinks: "refresh", role: "subscribe-to-interest"] do %>
    <span><%= gettext("Subscribe") %></span>
  <% end %>
<% end %>