web/router.ex
defmodule Constable.Router do
  use Phoenix.Router
  use Honeybadger.Plug

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash

    if Mix.env == :test do
      plug Constable.Plugs.SetUserIdFromParams
    end

    plug Constable.Plugs.FetchCurrentUser
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Constable do
    pipe_through :browser

    resources "/session", SessionController, only: [:new, :delete], singleton: true

    resources "/unsubscribe", UnsubscribeController, only: [:show]

    if Mix.env == :dev do
      get "/emails/:email_name", EmailPreviewController, :show
    end
  end

  scope "/", Constable do
    pipe_through [:browser, Constable.Plugs.RequireWebLogin]

    get "/", HomeController, :index

    resources "/announcements", AnnouncementController, only: [:index, :show, :new, :create, :edit, :update] do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/subscriptions", SubscriptionController, singleton: true, only: [:create, :delete]
    end
    resources "/settings", SettingsController, singleton: true, only: [:show, :update]
    resources "/interests", InterestController, only: [:index, :show], param: "id_or_name" do
      resources "/slack_channel", SlackChannelController, singleton: true, only: [:edit, :update, :delete]
      resources "/user_interest", UserInterestController, singleton: true, only: [:create, :delete]
    end
    resources "/search", SearchController, singleton: true, only: [:show, :new]
    resources "/recipients_preview", RecipientsPreviewController, singleton: true, only: [:show]
    resources "/user_activations", UserActivationController, only: [:index, :update]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", Constable do
    pipe_through :api

    resources "/email_forwards", EmailForwardController, only: [:create]
    resources "/email_replies", EmailReplyController, only: [:create]
  end

  scope "/auth", alias: Constable do
    pipe_through [:browser]

    get "/", AuthController, :index
    get "/javascript_callback", AuthController, :javascript_callback
    get "/browser_callback", AuthController, :browser_callback
  end

  scope "/auth", alias: Constable do
    pipe_through :api

    post "/mobile_callback", AuthController, :mobile_callback
  end

  scope "/api", as: :api, alias: Constable.Api do
    pipe_through [:api, Constable.Plugs.RequireApiLogin]

    resources "/announcements", AnnouncementController
    resources "/comments", CommentController, only: [:create]
    resources "/interests", InterestController, only: [:index, :show, :update]
    resources "/searches", SearchController, only: [:create]
    resources "/subscriptions", SubscriptionController, only: [:index, :create, :delete]
    resources "/user_interests", UserInterestController, only: [:index, :show, :create, :delete]
    resources "/users", UserController, only: [:index, :show]
    resources "/users", UserController, only: [:update], singleton: true
  end

  scope "/api", as: :api, alias: Constable.Api do
    pipe_through :api

    resources "/users", UserController, only: [:create]
  end
end

web/controllers/settings_controller.ex
defmodule Constable.SettingsController do
  use Constable.Web, :controller

  alias Constable.User

  def show(conn, _params) do
    changeset = User.settings_changeset(conn.assigns.current_user)
    render conn, "show.html", changeset: changeset, layout: false
  end

  def update(conn, %{"user" => user_params}) do
    changeset = User.settings_changeset(conn.assigns.current_user, user_params)

    case Repo.update(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:success, "YES!")
        |> render("show.html", changeset: changeset, layout: false)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> put_flash(:error, gettext("Something went wrong!"))
        |> render("show.html", changeset: changeset, layout: false)
    end
  end
end

web/views/settings_view.ex
defmodule Constable.SettingsView do
  use Constable.Web, :view
end

web/templates/settings/show.html.eex
<div class="modal-container">
  <div class="modal-overlay"></div>
  <div class="modal">
    <header>
      <h2>Profile and Settings</h2>
      <a href="#" class="modal-close">
        <img src="../images/icon-close.svg" />
      </a>
    </header>

    <%= form_for @changeset, settings_path(@conn, :update), [class: "settings-form"], fn(f) -> %>
      <div class="modal-body">
        <div class='field'>
          <label>Your name:</label>
          <%= text_input f, :name %>
          <%= error_tag f, :name %>
        </div>
        <div class='field'>
          <label class="switch-container">
            <div class="onoffswitch">
              <%= checkbox f, :auto_subscribe, class: "onoffswitch-checkbox" %>
              <label class="onoffswitch-label" for="user_auto_subscribe">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          Subscribe to me to announcements I’m interested in.
          </label>
        </div>
        <div class='field'>
          <label class="switch-container">
            <div class="onoffswitch">
              <%= checkbox f, :daily_digest, class: "onoffswitch-checkbox" %>
              <label class="onoffswitch-label" for="user_daily_digest">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          Send me daily digest emails about what's new on Constable.
          </label>
        </div>
      </div>

      <footer>
        <%# <%= link "Logout of Constable", to: session_path(@conn, :delete), method: :delete %1> %>
        <%= submit gettext("Save") %>
      </footer>
    <% end %>
  </div>


  <script>
    require('web/static/js/settings-form-modal').default();
  </script>
</div>